services:
  mnist-ann-project:
    build:
      context: .
      args:
        - KERNEL_NAME=${PROJECT_NAME:-mnist-ann-project}
    image: ${PROJECT_NAME:-mnist-ann-project}
    container_name: ${PROJECT_NAME:-mnist-ann-project}
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    ports:
      - "8888:8888" # Jupyter Notebook
    environment:
      - KERNEL_NAME=${PROJECT_NAME:-mnist-ann-project}
